version: 2.1
orbs:
  terraform: circleci/terraform@2.1.0

commands:
  reattach:
    steps:
      - attach_workspace:
         at: .


jobs:
  checkout:
    docker: 
      - image: cimg/base:2021.03
    steps:
      - checkout
      - run: base64 --decode $BASE64_TFVARS > ./testing.auto.tfvars
      - persist_to_workspace:
          root: ./
          paths:
            - . 
  fmt:
    executor: terraform/default
    steps:
      - reattach
      - terraform/fmt
  validate:
    executor: terraform/default
    steps:
      - reattach
      - terraform/validate
  sandbox-deploy:
    executor: terraform/default
    steps:
      - reattach
      - terraform/apply
      - persist_to_workspace:
          root: ./
          paths:
            - ./terraform.tfstate
  sandbox-cleanup:
    executor: terraform/default
    steps:
      - reattach
      - terraform/destroy

workflows:
  version: 2
  main:
    jobs:
      - checkout
      - fmt:
          requires: 
            - checkout
      - validate:
          context: tf-testing
          requires: 
            - checkout
      - sandbox-deploy:
          context: tf-testing
          requires:
            - validate
          filters:
            branches:
              only:
                - master
                - main
                - dev
      - hold:
          type: approval
          requires:
            - sandbox-deploy
      - sandbox-cleanup:
          context: tf-testing
          requires: 
            - hold
