version: 2.1
orbs:
  terraform: circleci/terraform@1.3.1

jobs:
  checkout:
    docker: 
      - image: cimg/base:2021.03
    steps:
      - checkout   
      - persist_to_workspace:
          root: ./
          paths:
            - . 
  validate:
    executor: terraform/default
    steps:
      - attach_workspace:
         at: .
      - terraform/fmt
      - terraform/validate
  sandbox-deploy:
    executor: terraform/default
    steps:
      - attach_workspace:
         at: .
      - terraform/apply
  sandbox-cleanup:
    executor: terraform/default
    steps:
      - checkout
      - terraform/destroy

workflows:
  version: 2
  main:
    jobs:
      - checkout
      - validate:
          context: tf-testing
          requires: 
            - checkout
      - sandbox-deploy:
          context: tf-testing
          requires:
            - validate
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - sandbox-deploy
      - sandbox-cleanup:
          context: tf-testing
          requires: 
            - hold
